### ISSUE TITLE
Create a small test gui to try out Pygtk.

### ISSUE THREAD

**Issue by Doomfest** [space-concordia-robotics/robotics-basestation#4]
Just trying out pygtk to see if it is a good candidate for making a gui and hte features that we need.

**Comment by Doomfest** [comment]
Hey guys, we can't just close issues without working code. If you have code for this specific issue please comment here and push your code to a branch for a pull request so we can take a look at it. I am reopening this issue untill this is done. Also, get on slack to see fi you want to talk to someone on the team in realtime.

I am testing this. I'll close this issue when I am done with pygtk-test.

**Comment by SamanthaSpace** [comment]
I deleted this issue because we decided not to use GTK, but rather PIL and I said that on another thread so I thought it best not to spam your inbox repeating things, but I guess I wasn't clear. The things they both do are too similar for it to be practical to use both.  Why are you testing this? I thought you were working on the networking code.

**Comment by psyomn** [comment]
FWIW, the gtk window looks good. If you find that it's easier to use and _has more features_ than the other libraries (or at least the features we critically need), then stick with this.

**Comment by Doomfest** [comment]
Take a look at the test-pygtk branch if you want to an example with gui. I will close this now.
